NFS-e Migrate/002-nfse-EnvioNFSe.feature
Aprova aí @carlamcury  o teste : )
=> Teste Pull Request

Jira/atp-6.feature
Pull Request para documentação do processo ATP
=> ATP-6:Criação de um teste ficticio pra documentação do processo ATP

Jira/ATP-13.feature
Criação de um Encomenda de Venda, com cálculo de PIS/COFINS Retido + PIS/COFINS Faturamento
=> ATP-13 - Encomenda de Venda com PIS Cofins Faturamento e Retido

Jira/ATP-12.feature
Criação de um Orçamento de Venda (GESSQH), com cálculo de PIS/COFINS Retido + PIS/COFINS Faturamento
=> ATP-12 - GESSQH Calculo de PIS COFINS Nao Cumulativo e Retido

Jira/ATP-25.feature
O cenário mais lindo que fiz na vida kkkkkkkkkkkkkkkk
=> ATP-25 - adaptação no ambiente de ATP

Jira/ATP-31.feature
Created new feature for GESPTH > GESPNH standard flow (no add-on)
Created and tested on AX3-QA ATP folder:
=> ATP-31 - GESPTH > GESPNH standard flow

Jira/ATP-15.feature
Criar Devolução de Compras Parcial com IPI Parcial
=> ATP-15 - GESPNH Parcial com IPI

Jira/ATP-18.feature
Criar Fatura de Vendas com PIS/COFINS inferior a 0,01 e transmitir para a SEFAZ
=> ATP-18 - Criar SIH com valor de PIS COFINS 0,01

Jira/ATP-9.feature
Criado cenário para validação da sugestão do municipio de prestação do serviço.
GESSOH -> GESSIH
=> ATP-9 Sugestão do municipio de prestação do serviço

Jira/ATP-37.feature
Foi criado o cenário para criação e duplicação de expedição sem a legislação brasileira
=> ATP-37 Criação cenario 3

Jira/ATP-8.feature
Realizar a Transmissão da NFSe Migrate através da Função CONSXQRPS
=> ATP-8 - Transmissão NFSe Migrate

Jira/ATP-35.feature
Correção referente ao nome da feature estar diferente do nome do arquivo (feature ATP-35).
=> ATP-35:Correção nome do arquivo diferente da feature

Jira/ATP-26.feature
Garantir a Criação de faturas através do botão na rotina de gestão de contratos
=> ATP-26 - Criar Fatura através da Função GESCON

Jira/ATP-38.feature
Garantir que os campos da legislação brasileira estão desabilitados na criação de Encomenda de Compra com estabelecimento não BR
=> ATP-38 - Criar GESSOH sem campos da Legislação Brasileira

Jira/ATP-39.feature
Garantir que os campos da legislação brasileira estão desabilitados na criação de Recepção de Compra com estabelecimento não BR
=> ATP-39 - GESPTH2 sem campos da legislacao brasileira

Jira/ATP-40.feature
Garantir que os campos da legislação brasileira estão desabilitados na criação de Fatura de Compra com estabelecimento não BR
=> ATP-40 - GESPIH sem campos da legislacao brasileira

SIH/xq-xqnfemonit-sih.feature
=> ATP-30 Ajuste feature quebrada

Jira/ATP-64.feature
Correção Cenário Attachments ATP-64.
=> ATP-64: Correç

Jira/ATP-47.feature
Garantir que a encomenda de venda criada automaticamente por Inter-estab. tenha os impostos calculados
=> ATP-47 - Encomenda de venda criada automaticamente por Inter-estab

Jira/ATP-72.feature
Garantir a criação e autorização de numa Nota adicional (GESXQADD) de uma GESSDH
=> ATP-72 - Garantir a criação e autorização da GESXQADD de uma GESSDH

Jira/ATP-73.feature
New feature creation, tested and OK:
=> ATP-73 New feature

Jira/ATP-60.feature
Feature para garantir que ao autorizar uma devolução de subcontratação o XML é anexado ao SRS criado.
=> ATP-60 Garante que o XML é anexado ao autorizar uma devolução de subcontratação

Jira/ATP-74.feature
=> ATP-74 New feature

Jira/ATP-76.feature
Garantir a criação e autorização de numa Nota adicional (GESXQADD) de uma GESSRH
=> ATP-76 - Garantir a criação e autorização da Nota adicional (GESXQADD) de uma GESSRH

Jira/ATP-75.feature
=> Atp 75 - Teste efetuado ambiente QA com sucesso

Jira/ATP-78.feature
=> ATP-78 - ATP-78

Jira/ATP-70.feature
Garantir cálculo correto para ICMS-ST para GESPNH Parcial
=> ATP-70 - Garantir cálculo correto para ICMS-ST para GESPNH Parcial

Jira/ATP-32.feature, Jira/ATP-33.feature, Jira/ATP-34.feature, Jira/ATP-35.feature, Jira/ATP-36.feature, Jira/ATP-37.feature, Jira/ATP-38.feature, Jira/ATP-39.feature, Jira/ATP-40.feature
Além da melhoria nas validações, também foram realizadas correções pontuais em algumas das features.
=> ATP-85 Alteração dos cenários para incluir validação dos botões XQBR em cada uma das features

Jira/ATP-54.feature
Novo Cenário de "Devolução do cliente” ao criar uma devolução com quantidade fracionada, o valor total dos Produtos é igual à entrega na origem (SDH).
=> ATP-54 -Devolução Cliente com quantidade fracionada 

Jira/ATP-76.feature
Alteração para edição das linhas na GESXQSADD
=> ATP-76 - Alteração para edição das linhas na GESXQSADD

Jira/ATP-66.feature
=> ATP-66 Correção

Jira/ATP-66.feature
Correção ATP 66 - Script Dev Simbol.
=> ATP-66-Correção

Jira/ATP-46.feature
=> Alterado para usar carteira TecnoSpeed

SADD/xq-s-flow-sadd-sih.feature
=> Incluido data do vencimento para XQSADD

Jira/ATP-46.feature
=> Resolvendo todos os conflitos

Jira/ATP-32.feature
=> Resolvendo b.o dos prints

Jira/ATP-92.feature
Novo Cenario do Ticket X3DEV-1194 para considerar na VTAX apenas o Campo LC116
=> ATP-92 - VTAX LC116

Jira/ATP-95.feature
Novo Cenário com Calculo do DIFERIMENTO DO ICMS nas Funções GESSOH e GESSIH
=> ATP-95 - GESSOH GESSIH COM DIFERIMENTO DE ICMS

Jira/ATP-95.feature
=> APT-95 - Alteração no Campo TOTICMSDIF

SAM-MIG/xq-gesxqadd-ipi-pis-cofins.feature
Correção na forma de selecionar o campo (definindo-o como tipo data), para que seja aplicada a função de preenchimento de data.
=> ATP-98 Correção feature xq-gesxqadd-ipi-pis-cofins

SAM-MIG/xq-s-crud-sqh-print.feature
Ajuste na parte da deleção do documento, para clicar no OK e confirmar a ação de apagar o documento.
=> ATP-99 Correção do DELETE no xq-s-crud-sqh-print

Jira/ATP-93.feature
Garantir que a valorização do stock esteja coerente no processo de importação na Recepção de Compra (GESPTH2)
=> ATP-93 - Novo Cenário de Valorização de Estoque no Processo de Importação

Jira/ATP-97.feature
Garantir o correto rateio dos elementos de faturação em uma nota de crédito
=> ATP-97 - Garantir o correto rateio dos elementos de faturação em uma nota de crédito

Jira/ATP-103.feature
Selecionar um expedição na devolução cliente e NÃO ser exibido a mensagem erro: Não é possível realizar o picking pois a NF-e não foi transmitida para sefaz - X3DEV-1833
=> ATP-103 - GESSRH Picking Expedição

Jira/ATP-102.feature
Alteração no Step 4, pois os campos no Jenkins são Diferentes
De = WK2ALLXQ_TOTMERCA // Para = XQSOH1_TOTMERCA
De = WK2ALLXQ_TOTDESCDESON // Para = XQSOH1_TOTDESCDESON
De = WK2ALLXQ_TOTNF // Para = XQSOH1_TOTNF
=> ATP-102 - Ajustes no Cenario

Jira/ATP-34.feature
Alterado para ultilizar outro estab (NA011) pois o PT032 precisa de passo adicionais.
=> ATP-34 Alterado para usar FCY NA001

Jira/ATP-61.feature
Alterado o nome do campo na grid após mudanças no Core que quebraram a feature.
=> ATP-61 Alteração para adequar novo nome do campo

Jira/ATP-94.feature
=> ATP-94 - Alteração da Chave da NF

Jira/ATP-106.feature
Novo Cenário de Municipalidade de Origem - X3DEV-2029
=> ATP-106 - Novo Cenario Municipalidade de Origem

Jira/ATP-47.feature
ATP-47 ajuste na forma de referenciar os campos do Summary da SOH ao invés DE: "X3 field name", PARA "name"
=> ATP-47 Ajuste na referência ao campo do Summary

Jira/ATP-105.feature
Novo Cenário para não permitir a exclusão da GESSDH quando estiver Validado/Transmitido
=> ATP-105 - Novo Cenario GESSDH

Jira/ATP-113.feature
Novo Cenário de MDFe com Cancelamento pela própria Função GESXQMDFE
=> ATP-113 - Cenario MDFE Cancelamento

Jira/ATP-111.feature, SAM-MIG/xq-p-flow-pih-cfop-suggestion.feature
Novo Cenário de MDFe com Encerramento pela própria Função GESXQMDFE
=> ATP-111 - Cenario MDFe Encerramento

Jira/ATP-112.feature
Novo Cenário de MDFe Encerramento pelo função de Monitoramento
=> ATP-112 - Cenario MDFE Encerramento Monitoramento

Jira/ATP-116.feature
Novo Cenário de MDFe selecionando 2 documentos
=> ATP-116 - MDFe com 2 Documentos

Jira/ATP-109.feature
Novo Cenário de Validação do documento em Anexo DAMDFE após criar uma MDFE, transmitir e encerrar
=> ATP-109 - Novo Cenario de Validação da DAMDFE

Jira/ATP-115.feature
Garantir que ao Transmitir uma GESSDH Não seja cancelada antes de estar Validada
=> ATP-115 - Novo Cenário GESSDH

Jira/ATP-119.feature
Novo cenário "caminho feliz" geração de remessa SISPAG
=> ATP-119 - SISPAG título com cod. de barras

Jira/ATP-118.feature
Cenário Completo Originado em Pedido de Compras até Fatura de Compras
=> ATP-118 - Novo Cenario da GESPSH ATÉ GESPIH

Jira/ATP-117.feature
Novo Cenário de Nota de Crédito de Fatura de Compra Serviço - Não exigir documento referenciado
=> ATP-117 - Cenario NDC não exigir doc referenciado

Jira/ATP-109.feature, Jira/ATP-111.feature, Jira/ATP-112.feature, Jira/ATP-113.feature, Jira/ATP-114.feature, Jira/ATP-116.feature, Jira/ATP-38.feature
Ajuste de parametrizações para evitar a tela de "Requirements to consider"e correção das features ATP-109 a ATP-116 para as traduções das rotinas de MDF-e.
=> ATP-108 ajustes parametrização e tradução MDF-e

Jira/ATP-122.feature
Cenário de Nota de Crédito de Fatura de Compra Serviço, para Não exigir documento referenciado, conforme o ticket X3DEV-2288
=> ATP-122 - Não exigir doc referenciado para serviço

Jira/ATP-123.feature
Novo Cenário de GESPTH com Elemento de faturação AFRMM e não sendo duplicado no FRETE, Com 2 Linhas e Quantidades Diferentes
=> ATP-123 - GESPTH com Rateio de AFRMM

Jira/ATP-25.feature
Após atualizações nas colunas da tabela XQINVOICE, atualizada a posição do campo editado na feature.
Validado no ambiente Jenkins - ATP.
=> ATP-25 Atualização da posição da coluna na GMAINT

Jira/ATP-125.feature
Novo Cenário de Nota Complementar para que não ocorra o Erro "Requisição não pode ser Nula"
=> ATP-125 - GESXQSADD REQUISIÇÃO NÃO PODE SER NULA

Jira/ATP-127.feature
Cenário onde na RTAX, as incidências determinam que o Desconto deve deduzir da BC do IPI
=> ATP-127 - Desconto Deduz na BC do IPI

Jira/ATP-136.feature
Cenário de Geração dos Arquivos de Integração - Cenário 7 - Inventário
=> ATP-136 - Cenario Arq integração Inventario

Jira/ATP-135.feature
Cenário de Geração dos Arquivos de Integração - Cenário 6 - Bloco K
=> ATP-135 Cenario Arq Integração Bloco K

Jira/ATP-134.feature
Cenário de Geração dos Arquivos de Integração - Cenário 5 - Todos Produtos
=> ATP-134 Cenario Arq integração Todos os Produtos

Jira/ATP-133.feature
Cenário de Geração dos Arquivos de Integração - Cenário 4 - Produtos
=> ATP-133 Cenario Arq integração Produtos

Jira/ATP-132.feature
Cenário de Geração dos Arquivos de Integração - Cenário 3 - Notaent
=> ATP-132 - Cenario Arq integração NOTAENT

Jira/ATP-131.feature
Cenário de Geração dos Arquivos de Integração - Cenário 2 - Notasai (XML)
=> ATP-131 - Cenario Arq integração NOTASAI XML

Jira/ATP-130.feature
Cenário de Geração dos Arquivos de Integração - Cenário 1 - Notasai (txt)
=> ATP-130 - Arquivo de Integração NOTASAI txt

Jira/ATP-128.feature
GESSOH Manual não deve sobrepor a Operação Fiscal Inter-Estab. / GESSOH Automatica deve respeitar a parametrização Operação Fiscal da ADPVAL
=> ATP-128 - SUGESTÃO OPF GESSOH INTER-ESTAB

Jira/ATP-118.feature
Adicionado a instrução "user waits 3 seconds" como correção à issue do botão Close ainda não estar disponível para clique nas ações do cenário 5. View PR Orders - Num. GESPOH.
=> ATP-118 Fix do erro botão Close "not clickable"

Jira/ATP-129.feature
Sugestão CST nas devoluções de empréstimo respeitando a seguinte hierarquia: Artigo Estab. → Artigo → CFOP
Correção do Jira: X3DEV-2823
=> ATP-129 - Cenario de Sugestão CST GESSRL

Jira/ATP-137.feature
Cenário referente a Correção do BUG X3DEV-2946, para que as observações adicionais não sejam duplicadas conforme o número de linhas
=> ATP-137 - Cenario de Duplicação das Observacoes Adicionais

Jira/ATP-138.feature
Cenario do Ticket DEV 3193, para carregar elementos de faturação ao criar encomenda a partir do orçamento
(Teste realizado criando a encomenda direta e também saindo da função e retornando)
=> ATP-138 - Cenario do Ticket DEV 3193

Jira/ATP-139.feature
Cenário referente ao ticket X3DEV-3088
Ao informar dados de transporte, gravar o documento, retirar estas informações e regravar, não deve ocorrer problemas com a transmissão do documento.
=> ATP-139 - Cenário do Ticket X3DEV-3088

Jira/ATP-140.feature
Cenario do Ticket X3DEV-3276
Tipo de nota complementar CT-e ter o Resumo preenchido corretamente quando salva o documento
=> ATP-140 - Nota Complementar CTe - Resumo Preenchido Corretamente

Jira/ATP-142.feature
Cenário de Rejeição da NFe: Chave de Acesso inválida (modelo diferente de 65) conforme o  ticket Jira: X3DEV-3410, onde ao retornar o contador para um número que já foi utilizado, o sistema vai autorizar o documento conforme aquele já existente.
=> ATP-142 - Cenário de Rejeição da NFe: Chave de Acesso inválida

Jira/ATP-146.feature
Cenário de Vencimentos da Nota Complementar GESXQSADD conforme o ticket X3DEV-3711
=> ATP-146 - Vencimentos GESXQSADD ticket X3DEV-3711

Jira/ATP-144.feature
Cenário de Cálculo de impostos Expedição [GESSDH] conforme o Ticket X3DEV-3814
=> ATP-144 - Cálculo de impostos Expedição [GESSDH]

Jira/ATP-147.feature
GESPNH Manual, ao inserir os impostos no detalhamento, o mesmo deve reflete em dados legais
O Processo Original é decorrente de um ponto de entrada, e não é possível replicar este PE devido a necessidade de ter um Específico
Jira: X3DEV-3967
=> ATP-147 - GESPNH Detalhamento de Impostos

Jira/ATP-56.feature
Alterado a Discriminação do RPS para Serviço Generico !CHR13!PIS COFINS Retido (Linha 162)
=> ATP-56 - Alterações Discriminação

Jira/ATP-144.feature
Alterado os Valores de Validação dos Impostos (Linha 65 até 75)
=> ATP-144 - Alterado Valores

Jira/ATP-145.feature
Elementos de Faturação valorizando estoque na DI Unica
=> ATP-145 - Elementos de Faturação na DI Unica

Jira/ATP-150.feature
SUGESTÃO CST IPI NA GESSQH, CONFORME O TICKET X3DEV-4318
=> ATP-150 - SUGESTÃO CST IPI NA GESSQH

Jira/ATP-149.feature
CONTABILIZAÇÃO GESXQSADD SEM EDITAR VENCIMENTOS CONFORME O TICKET X3DEV-4184
=> ATP-149 - CONTABILIZAÇÃO GESXQSADD SEM EDITAR VENCIMENTOS

Jira/ATP-122.feature
Efetuado ajustes nas linhas 123 até 127 para não gerar erro no cenário, conforme relatório do JENKINS
=> ATP-122 - Ajustes efetuados para não ocorrer erro no Cenário

Jira/ATP-153.feature
Sistema disponibiliza a opção do usuário inserir os dados de transporte no Orçamento de Venda
OBS: Teste efetuado pelo picking do Orçamento na Encomenda
Jira: X3DEV-4429
=> ATP-153 - Dados de Transporte no Orçamento atraves de picking na encomenda

Jira/ATP-151.feature
Sistema disponibiliza a opção do usuário inserir os dados de transporte no Orçamento de Venda
OBS: Teste efetuado pelo botão Order no Orçamento
Jira: X3DEV-4429
=> ATP-151 - Dados de Transporte no Orçamento pelo Botao Order

Jira/ATP-154.feature
Expedição Parcial deve trazer valores parciais no resumo conforme o Ticket X3DEV-4518
=> ATP-154 - Expedição Parcial deve trazer valores parciais no resumo

Jira/ATP-156.feature
Novo Cenário para Permitir a Alteração de Vencimento na Fatura de Venda
=> ATP-156 - Permitir a Alteração de Vencimento na Fatura de Venda

Jira/ATP-155.feature
Novo Cenário para Permitir a Alteração de Vencimento na Fatura de Compra
=> ATP-155 - Permitir a Alteração de Vencimento na Fatura de Compra

Jira/ATP-159.feature
Processo de Fluxo de Caixa, criando a Encomenda, FUNTRTCFO e GESCFO
OBS: Precisamos replicar os parâmetros do Estab. FCBR1 nos demais ambientes de testes automatizados
=> ATP-159 - Fluxo de Caixa

Jira/ATP-158.feature
Gerar uma Fatura de Venda GESSIH, com Retenções preenchida, e com um único vencimento, as retenções devem deduzir do vencimento.
=> ATP-158 - GESSIH com Retenções devem deduzir do único vencimento

Jira/ATP-161.feature
Gerar uma Fatura de Venda GESSIH, com Retenções preenchida, e com vários vencimento, as retenções devem deduzir dos vencimentos.
=> ATP-161 - GESSIH com retenções, e deve deduzir de vários vencimentos

Jira/ATP-162.feature
Somente Retenção de PIS COFINS CSLL deve deduzir do vencimento
=> ATP-162 - Somente Retenção de PIS COFINS CSLL deve deduzir do vencimento

Jira/ATP-163.feature
Somente Retenção de ISS deve deduzir do vencimento
=> ATP-163 - Somente Retenção de ISS deve deduzir do vencimento

Jira/ATP-164.feature
GESSQH-GESSOH - Dados Exportação
=> ATP-164 - GESSQH-GESSOH - Dados Exportação

Jira/ATP-165.feature
Geração do ICMS ST cobrado anteriormente
=> ATP-165 - Geração do ICMS ST cobrado anteriormente

Jira/ATP-166.feature, Jira/ATP-167.feature
Elementos de faturação Desconto R$ e frete preenchido na Encomenda, Expedição e Fatura de Venda conforme Jira: X3DEV-5369
=> ATP-167 - Desconto e frete na GESSOH, GESSDH, E GESSIH

Jira/ATP-103.feature, Jira/ATP-166.feature, Jira/ATP-52.feature, Jira/ATP-54.feature, Jira/ATP-58.feature, Jira/ATP-71.feature, Jira/ATP-76.feature, SAM-MIG/05010501-CST10.feature, SAM-MIG/05010502-CST30.feature, SAM-MIG/05010503-CST70.feature, SAM-MIG/05010504-CST90.feature, SAM-MIG/05010505-CST201.feature, SAM-MIG/05010506-CST202.feature, SAM-MIG/05010507-CST900.feature, SAM-MIG/xq-s-flow-srh-pick-sdh.feature
Alterado nome do campo XQSRH1_CODOPF para WK6ALLXQ_CODOPF
=> Fix alll WK6ALLXQ_CODOPF

Jira/ATP-170.feature
Carta de correção deve habilitar a exclusão quando não estiver validada
=> ATP-170 - Carta de correção

Jira/ATP-116.feature, Jira/ATP-135.feature, Jira/ATP-136.feature, Jira/ATP-158.feature, Jira/ATP-23.feature, Jira/ATP-32.feature, Jira/ATP-94.feature, SAM-MIG/05020101-CST10.feature, SAM-MIG/05020102-CST30.feature, SAM-MIG/05020103-CST70.feature, SAM-MIG/05020104-CST90.feature, SAM-MIG/05020105-CST201.feature, SAM-MIG/05020106-CST202.feature, SAM-MIG/05020107-CST900.feature, SAM-MIG/xq-p-flow-pth-crud.feature
Erros apresentados no JENKINS e feito as correções
=> ATP-AJUSTES - Erros apresentados no JENKINS e feito as correções

Jira/ATP-11.feature, Jira/ATP-12.feature, Jira/ATP-13.feature, Jira/ATP-161.feature, Jira/ATP-25.feature, Jira/ATP-32.feature, Jira/ATP-72.feature, Jira/ATP-76.feature, Jira/ATP-77.feature, Jira/ATP-78.feature, Jira/ATP-81.feature, Jira/ATP-82.feature
=> ATP- Ajustes

Jira/ATP-122.feature, Jira/ATP-125.feature, Jira/ATP-137.feature, Jira/ATP-14.feature, Jira/ATP-140.feature, Jira/ATP-142.feature, Jira/ATP-143.feature, Jira/ATP-162.feature, Jira/ATP-163.feature, Jira/ATP-164.feature
AJUSTADO OS SEGUINTES CENÁRIOS ATP (14/122/125/137/140/142/143/162/163/164)
=> ATP-AJUSTES - Ajustado cenários que estavam com problema no QA

Jira/ATP-51.feature, SAM-MIG/xq-p-crud-gespoh.feature, SAM-MIG/xq-p-flow-poh-pth-imp-icms.feature, SAM-MIG/xq-p-flow-poh-pth-imp-imptx.feature, SAM-MIG/xq-p-flow-pth-02.feature, SAM-MIG/xq-p-flow-pth-03.feature, SAM-MIG/xq-p-flow-pth-al.feature, SAM-MIG/xq-p-flow-pth-imp-icms.feature, SAM-MIG/xq-p-flow-pth-imp-imptx.feature, SAM-MIG/xq-p-flow-pth-pnh.feature
Ajuste da posição dos comando de seleção da tab e da grid. 
Deixando de fora do scenario outline.
=> ATP Ajustes - mais ajustes nos scenario outline

Jira/ATP-116.feature, Jira/ATP-165.feature, Jira/ATP-166.feature, Jira/ATP-167.feature, Jira/ATP-75.feature, Jira/ATP-79.feature, Jira/ATP-80.feature
Correções em Cenários no ATP QA
=> ATP-AJUSTES - Correções em Cenários no ATP QA

Jira/ATP-129.feature, Jira/ATP-143.feature, Jira/ATP-71.feature
=> ATP-AJUSTES nos Cenarios

Jira/ATP-46.feature, Jira/ATP-59.feature, Jira/ATP-75.feature, Jira/ATP-93.feature, SAM-MIG/xq-p-flow-pnh-cfop-suggestion.feature, SAM-MIG/xq-p-flow-pth-01.feature, SAM-MIG/xq-p-flow-pth-cfop-suggestion.feature, SAM-MIG/xq-p-flow-pth-imp-ii.feature
=> ATP-AJUSTES - Correções em Cenarios

SAM-MIG/ATP-100.feature
=> ATP-100 - Rateio de IPI nos Vencimentos

Jira/ATP-173.feature
Fatura de Consumidor Final não Identificado Ticket X3DEV-6556
=> ATP-173 - Fatura de Consumidor Final não Identificado

Jira/ATP-90.feature
Criar Carta de Correção Selecionando Fatura de Venda
=> ATP-90 - Criar Carta de Correção Selecionando Fatura de Venda

Jira/ATP-20.feature
Criar Carta de Correção Selecionando Fatura de Compra
=> ATP-20 - Criar Carta de Correção Selecionando Fatura de Compra

Jira/ATP-172.feature
Recepção com casas decimais, na fatura não pode ter desvio (-0.00) no Controlo
=> ATP-172 - GESSIH não pode apresentar desvio -0,00

Jira/ATP-169.feature, Jira/ATP-36.feature, SAM-MIG/xq-p-flow-pnh-cfop-suggestion.feature, SAM-MIG/xq-p-flow-poh-pth-imp-txac.feature, SAM-MIG/xq-p-flow-pth-pih.feature
=> Atp ajustes

Jira/ATP-157.feature
GESPOH com Elemento de Faturação Frete e 2 Linhas, ao alterar o Peso deve ratear o elemento de faturação corretamente
=> ATP-157 - Rateio Elemento Fat por Peso

Jira/ATP-173.feature
=> ATP-173 - Ajustado o Cliente para BR007

Jira/ATP-68.feature
Garantir que gere o contrato de serviço pela função FUNAUTINVC
=> ATP-68 - Garantir que gere o contrato de serviço pela função FUNAUTINVC

Jira/ATP-122.feature, Jira/ATP-94.feature
=> ATP-AJUSTES - Correções de Cenários

Jira/ATP-137.feature, Jira/ATP-25.feature, Jira/ATP-46.feature, Jira/ATP-82.feature
ATP-AJUSTES - Correcao em scenarios
=> ATP-AJUSTES - Correcao em scenarios

Jira/ATP-25.feature
ATP-AJUSTES - CORRECAO CENARIO ATP 25
=> ATP-AJUSTES - CORRECAO CENARIO ATP 25

Jira/ATP-88.feature
ATP-88 - CENARIO TAG RASTRO XML
=> ATP-88 - CENARIO TAG RASTRO XML

Jira/ATP-21.feature, SAM-MIG/xq-s-flow-sdh-al1.feature, SAM-MIG/xq-s-flow-sdh-al2.feature, SAM-MIG/xq-s-flow-sdh-al3.feature, SAM-MIG/xq-s-flow-sdh-al4.feature, SAM-MIG/xq-s-flow-sdh-al5.feature, SAM-MIG/xq-s-flow-sdh-al6.feature
Correção em Cenarios que apresentaram erros no Report 09/01/2025
=> ATP-AJUSTES - Correção em Cenarios

Jira/ATP-110.feature
Transmitir a Carta de Correção não deve gerar o problema XQCNSNFESTD$adx (743) Erro 7 : Classe inexistente [M:SIH0]
=> ATP-110 - Carta de Correcao

Jira/ATP-174.feature
Gerar o Grupo Correto de PIS ST e COFINS ST no XML com Regra Parametrizada para Alíquota Reais
=> ATP-174 - PIS COFINS ST

Jira/ATP-91.feature
Gerar o Grupo Correto de PIS ST e COFINS ST no XML com Regra Parametrizada para Alíquota Percentual
=> ATP-91 - PIS COFINS ST

Jira/ATP-148.feature
ISS deve considerar o valor correto na Transmissão da Fatura sem arredondar
=> ATP-148 - ISS Não arredondar

Jira/ATP-160.feature
Deduzir da Base de PIS/COFINS o ICMS + DIFAL
=> ATP-160 - Deduzir da Base de PIS/COFINS o ICMS + DIFAL

Jira/ATP-175.feature
Deduzir ICMS desonerado do PIS COFINS, conforme correção do ticket JIRA: X3DEV-7327
=> ATP-175 - Deduzir ICMS desonerado do PIS COFINS

Jira/ATP-175.feature, Jira/ATP-9.feature, Jira/ATP-91.feature, Jira/ATP-94.feature, SAM-MIG/xq-s-flow-sqh-sdh-tos2.feature
=> ATP-AJUSTES Corrções de Cenarios

Jira/ATP-156.feature, Jira/ATP-46.feature, Jira/ATP-87.feature
=> ATP-AJUSTESNOVO - Correções

Jira/ATP-87.feature, SAM-MIG/05020406-CST202.feature, SAM-MIG/05020407-CST900.feature, SAM-MIG/xq-p-flow-pih-oi.feature
=> ATP-AJUSTES3 - Correcoes

Jira/ATP-140.feature, Jira/ATP-157.feature
=> Atp ajustes3

Jira/ATP-177.feature
Arredondamento SIH - SRH - Bug X3DEV-8039
=> ATP-177 - Arredondamento SIH - SRH

Jira/ATP-181.feature
ATP-181 Custo Compra Nacional - UN>UN - PTH > PIH - Com elementos de Faturação Frete e Desconto, decorrente do ticket X3DEV-8284
=> ATP-181 - Custo de Stock UN UN com Elementos de Faturação

Jira/ATP-178.feature
Tg IndIntermed no XML conforme correção X3DEV-7814
=> ATP-178 - Tg IndIntermed no XML

Jira/ATP-185.feature
ATP 185 - Correção enquandramento de IPI
=> ATP 185 - Correção enquandramento de IPI
